---
- name: Remove generated secret template for Broker
  file:
    path: "{{ ar_osc_amqbroker_config_dest }}/amq-broker-secret.yml"
    state: absent
  changed_when: false

- name: Remove generated user properties template for Broker
  file:
    path: "{{ ar_osc_amqbroker_config_dest }}/artemis-users.properties"
    state: absent
  changed_when: false

- name: Remove generated secret files tempalte for Broker
  file:
    path: "{{ ar_osc_amqbroker_config_dest }}/amq-broker-files-secret.yml"
    state: absent
  changed_when: false

