---
- name: Remove generated secret template for Broker
  file:
    path: "{{ _ar_osc_amqbroker_config_dest_templates }}/amq-broker-secret.yml"
    state: absent
  changed_when: false

- name: Remove generated user properties template for Broker
  file:
    path: "{{ _ar_osc_amqbroker_config_dest_templates }}/artemis-users.properties"
    state: absent
  changed_when: false

- name: Remove generated secret files tempalte for Broker
  file:
    path: "{{ _ar_osc_amqbroker_config_dest_templates }}/amq-broker-secret-files.yml"
    state: absent
  changed_when: false

