---
# This pulls secrets into templates that can then be loaded into Openshift
# Note: Secret files are temporary and will be removed, so these are marked as unchanging
- name: Generate broker secrets template
  template:
    src: amq-broker-secret.yml.j2
    dest: "{{ _ar_osc_amqbroker_config_dest_templates }}/amq-broker-secret.yml"
  changed_when: false
  tags:
    - secrets

- name: Generate the users property file
  template:
    src: users.properties.j2
    dest: "{{ _ar_osc_amqbroker_config_dest_templates }}/artemis-users.properties"
  changed_when: false
  tags:
    - secrets

- name: Generate the roles property file
  template:
    src: roles.properties.j2
    dest: "{{ _ar_osc_amqbroker_config_dest_templates }}/artemis-roles.properties"

- name: Generate broker secret files template
  template:
    src: amq-broker-files-secret.yml.j2
    dest: "{{ _ar_osc_amqbroker_config_dest_templates }}/amq-broker-files-secret.yml"
  changed_when: false
  tags:
    - secrets
