---
- name: Seed OpenShift
  include_role:
    name: ar_os_seed
    tasks_from: seed
  vars:
    ar_os_seed_config_dest: "{{ _ar_osc_amqbroker_config_dest }}"
    ar_os_seed_namespace: "{{ ar_osc_amqbroker_ns }}"
    ar_os_seed_openshift_content: "{{ _ar_osc_amqbroker_openshift_content }}"
    ar_os_seed_openshift_login_url: "{{ ar_osc_amqbroker_openshift_login_url }}"
    ar_os_seed_registry_secrets: "{{ registry_secrets | default([]) }}"
